---
title: "Year1_Data_Prelim"
author: "Brent Campbell"
date: "June 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data2 <- read.csv(file="C:/Users/BCamp/Desktop/Capstone Project/DataYear5.csv", header=TRUE, sep=",")
str(data2)

idx <- data2 == "?"
is.na(data2) <- idx 
```

```{r}
data2[] <- lapply(data2, function(x) {
    if(is.factor(x)) as.numeric(as.character(x)) else x
})

sapply(data2, class)
str(data2)
```





```{r}
input.mean <- function(x) {
    z <- mean(x, na.rm = TRUE)
    x[is.na(x)] <- z
    return(x)
}

data.v3 <- lapply(data2, function(x){
    if(is.numeric(x) & any(is.na(x))){
            input.mean(x)
        } else {
            x
        }
    }
)

Year1 <- as.data.frame(data.v3)
str(Year1)
```

```{r}
mod <- glm(Bankruptcy.Outcome ~ ., data=Year1)
cooksd <- cooks.distance(mod)

plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 4*mean(cooksd, na.rm=T), col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>4*mean(cooksd, na.rm=T),names(cooksd),""), col="red")  # add labels

influential <- as.numeric(names(cooksd)[(cooksd > 4*mean(cooksd, na.rm=T))])
print(Year1[influential, ]) 
```

```{r}
Year1.screen <- Year1[-c(4385), ]
sum(is.na(Year1.screen))
str(Year1.screen)
```

```{r}
#Run coorelation assessment on Year1.screen
normalize <- function(x) {
               return ((x - min(x)) / (max(x) - min(x))) }
Year1.Norm <- prc_n <- as.data.frame(lapply(Year3.screen[1:62], normalize))
cor(Year1.Norm, Year1.Norm$Bankruptcy.Outcome)
```

```{r}
write.csv(Year1.Norm, "C:/Users/BCamp/Desktop/Capstone Project/Literature Review/Year1.Norm.csv")
```
