---
title: "Untitled"
author: "Brent Campbell"
date: "June 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
data <- read.csv(file="C:/Users/BCamp/Desktop/Capstone Project/DataYear3_v2.csv", header=TRUE, sep=",")
sum(is.na(data))

```

```{r}
input.mean <- function(x) {
    z <- mean(x, na.rm = TRUE)
    x[is.na(x)] <- z
    return(x)
}

data.v2 <- lapply(data, function(x){
    if(is.numeric(x) & any(is.na(x))){
            input.mean(x)
        } else {
            x
        }
    }
)

Year3 <- as.data.frame(data.v2)
str(Year3)
```

```{r}
mod <- glm(Bankruptcy.Outcome ~ ., data=Year3)
cooksd <- cooks.distance(mod)

plot(cooksd, pch="*", cex=2, main="Influential Obs by Cooks distance")  # plot cook's distance
abline(h = 4*mean(cooksd, na.rm=T), col="red")  # add cutoff line
text(x=1:length(cooksd)+1, y=cooksd, labels=ifelse(cooksd>4*mean(cooksd, na.rm=T),names(cooksd),""), col="red")  # add labels

influential <- as.numeric(names(cooksd)[(cooksd > 4*mean(cooksd, na.rm=T))])
print(Year3[influential, ]) 

```

```{r}
#Remove Rows Containing Outliers
Year3.screen <- Year3[-c(80,219,221,2232,5318,6255,7347,10354,10379,10461,10469,10480,10503), ]
sum(is.na(Year3.screen))
str(Year3.screen)

```
```{r}

#Run coorelation assessment on Year3.screen
normalize <- function(x) {
               return ((x - min(x)) / (max(x) - min(x))) }
Year3.Norm <- prc_n <- as.data.frame(lapply(Year3.screen[1:62], normalize))
cor(Year3.Norm, Year3.Norm$Bankruptcy.Outcome)
```

