---
title: "AnalyticalFile"
author: "Brent Campbell"
date: "July 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
Y1.Final <- read.csv(file="C:/Users/BCamp/Desktop/Capstone Project/Feature Selection/Year1Final.csv", header=TRUE, sep=",")

Y3.Final <- read.csv(file="C:/Users/BCamp/Desktop/Capstone Project/Feature Selection/Year3Final.csv", header=TRUE, sep=",")

str(Y1.Final)
str(Y3.Final)
summary(Y3.Final)
```


```{r}

#ANALYSIS 1-Year ADVANCE BANKRUPTCY PREDICTION

#RUN THE MACHINE LEARNING ALGORITHMS FOR LOGISTIC REGRESSION, SVM, NAiVE BAYES and DECISION TREE
install.packages("mlbench")
library(mlbench)

Y1.Final$Bankruptcy.Outcome <- as.factor(Y1.Final$Bankruptcy.Outcome)
str(Y1.Final)

install.packages("caret")
library(caret)
'%ni%' <- Negate('%in%') #define 'not in' func
options(scipen=999)

#SPLIT THE DATA SET INTO TRAINING AND TEST 
set.seed(100)
trainDataInd.Y1 <- createDataPartition(Y1.Final$Bankruptcy.Outcome, p=0.7, list = F)
trainData.Y1 <- Y1.Final[trainDataInd.Y1, ]
testData.Y1 <- Y1.Final[-trainDataInd.Y1, ]

dim(trainData.Y1); dim(testData.Y1)

#LOGISTIC REGRESSION MODEL 

model.Y1 <- glm(Bankruptcy.Outcome~., family=binomial(link='logit'),data=trainData.Y1)
summary(model.Y1)
anova(model.Y1, test="Chisq")
confusionMatrix(table(predict(model.Y1,type="response") >= 0.5, trainData.Y1$Bankruptcy.Outcome == 1))



```




```{r}
#SVM MODEL

#Train the SVM Model 
trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
set.seed(300)
 
svm_Linear.Y1 <- train(Bankruptcy.Outcome ~., data = trainData.Y1, method = "svmLinear",
                 trControl=trctrl,
                 preProcess = c("center", "scale"),
                 tuneLength = 10)
svm_Linear.Y1

#Test the prediction and confusion matrix 
test_pred_SVM <- predict(svm_Linear.Y1, newdata = testData.Y1)
test_pred_SVM
confusionMatrix(test_pred_SVM, testData.Y1$Bankruptcy.Outcome) 
```

```{r}
#Naive Bayes Model 
install.packages("mlr")
library(mlr)

NBtask.Y1 = makeClassifTask(data = Y1.Final, target = "Bankruptcy.Outcome")
selected_model.Y1 = makeLearner("classif.naiveBayes")

NB_mlr = train(selected_model.Y1, NBtask.Y1)
NB_mlr$learner.model

predictions_mlr = as.data.frame(predict(NB_mlr, newdata = Y1.Final[,1:12]))
table(predictions_mlr[,1],Y1.Final$Bankruptcy.Outcome)
```



```{r}
#CLASSIFICATION TREE MODEL 

install.packages("rpart")
install.packages("rattle")
library(rpart)
library(rattle)

Y1.tree <- rpart(Bankruptcy.Outcome~., data = trainData.Y1, method = "class")
Y1.tree

fancyRpartPlot(Y1.tree, main = "Bankruptcy Outcome")

```


```{r}
#ANALYSIS 1-Year ADVANCE BANKRUPTCY PREDICTION

#RUN THE MACHINE LEARNING ALGORITHMS FOR LOGISTIC REGRESSION, SVM, NAiVE BAYES, NEURAL NETWORKS, and DECISION TREE
install.packages("mlbench")
library(mlbench)

Y3.Final$Bankruptcy.Outcome <- as.factor(Y3.Final$Bankruptcy.Outcome)
str(Y3.Final)

install.packages("caret")
library(caret)
'%ni%' <- Negate('%in%') #define 'not in' func
options(scipen=999)

#SPLIT THE DATA SET INTO TRAINING AND TEST 
set.seed(200)
trainDataInd.Y3 <- createDataPartition(Y3.Final$Bankruptcy.Outcome, p=0.7, list = F)
trainData.Y3 <- Y3.Final[trainDataInd.Y3, ]
testData.Y3 <- Y3.Final[-trainDataInd.Y3, ]

dim(trainData.Y3); dim(testData.Y3)

#LOGISTIC REGRESSION MODEL 

model.Y3 <- glm(Bankruptcy.Outcome~., family=binomial(link='logit'),data=trainData.Y3)
summary(model.Y3)
anova(model.Y3, test="Chisq")
confusionMatrix(table(predict(model.Y3,type="response") >= 0.5, trainData.Y1$Bankruptcy.Outcome == 1))
```

```{r}
#SVM MODEL

#Train the SVM Model 
trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)
set.seed(400)
 
svm_Linear.Y3 <- train(Bankruptcy.Outcome ~., data = trainData.Y3, method = "svmLinear",
                 trControl=trctrl,
                 preProcess = c("center", "scale"),
                 tuneLength = 10)
svm_Linear.Y3

#Test the prediction and confusion matrix 
test_pred_SVM <- predict(svm_Linear.Y3, newdata = testData.Y3)
test_pred_SVM
confusionMatrix(test_pred_SVM, testData.Y3$Bankruptcy.Outcome) 
```


```{r}
#Naive Bayes Model 
install.packages("mlr")
library(mlr)

NBtask.Y3 = makeClassifTask(data = Y3.Final, target = "Bankruptcy.Outcome")
selected_model.Y3 = makeLearner("classif.naiveBayes")

NB_mlr = train(selected_model.Y3, NBtask.Y3)
NB_mlr$learner.model

predictions_mlr = as.data.frame(predict(NB_mlr, newdata = Y3.Final[,1:12]))
table(predictions_mlr[,1],Y3.Final$Bankruptcy.Outcome)
```


```{r}

Y3.tree <- rpart(Bankruptcy.Outcome~., data = trainData.Y3, method = "class")
Y3.tree

fancyRpartPlot(Y3.tree, main = "Bankruptcy Outcome")
```















































































